SET CLASSPATH_JARS=SVN_LOCAL/lib/static/junit/junit.jar;SVN_LOCAL/lib/static/log4j/log4j-1.2.8.jar

SET SRC_IMPLEMENTATION=SVN_LOCAL\implementation\src
SET SRC_JUNIT=SVN_LOCAL\junit\src

SET CLASSES_TO_COMPILE_IMPLEMENTATION=%SRC_IMPLEMENTATION%\com\dai\junit\example\*.java
SET CLASSES_TO_COMPILE_JUNIT=%SRC_JUNIT%\com\dai\junit\example\*.java

SET BUILD_CLASS_DIR_IMPLEMENTATION=BUILD_LOCAL\implementation\build\classes
SET BUILD_CLASS_DIR_JUNIT=BUILD_LOCAL\junit\build\classes

ECHO CLASSPATH_JARS=%CLASSPATH_JARS%
ECHO SRC_IMPLEMENTATION=%SRC_IMPLEMENTATION%
ECHO SRC_JUNIT=%SRC_JUNIT%
ECHO CLASSES_TO_COMPILE_IMPLEMENTATION=%CLASSES_TO_COMPILE_IMPLEMENTATION%
ECHO CLASSES_TO_COMPILE_JUNIT=%CLASSES_TO_COMPILE_JUNIT%
ECHO BUILD_CLASS_DIR_IMPLEMENTATION=%BUILD_CLASS_DIR_IMPLEMENTATION%
ECHO BUILD_CLASS_DIR_JUNIT=%BUILD_CLASS_DIR_JUNIT%

javac -sourcepath %SRC_IMPLEMENTATION% -cp %CLASSPATH_JARS% -d %BUILD_CLASS_DIR_IMPLEMENTATION% %CLASSES_TO_COMPILE_IMPLEMENTATION%

javac -sourcepath %SRC_IMPLEMENTATION% -cp %CLASSPATH_JARS%;%BUILD_CLASS_DIR_IMPLEMENTATION% -d %BUILD_CLASS_DIR_JUNIT% %CLASSES_TO_COMPILE_JUNIT%
