
SET CLASSPATH_JARS=SVN_LOCAL/lib/static/junit/junit.jar;SVN_LOCAL/lib/static/log4j/log4j-1.2.8.jar
SET BUILD_CLASS_DIR_IMPLEMENTATION=BUILD_LOCAL\implementation\build\classes
SET BUILD_CLASS_DIR_JUNIT=BUILD_LOCAL\junit\build\classes
SET RUN_CLASSPATH=%BUILD_CLASS_DIR_JUNIT%;%BUILD_CLASS_DIR_IMPLEMENTATION%;%CLASSPATH_JARS%
SET CLASS_TO_RUN=com.dai.junit.example.AddNumberTest

ECHO CLASSPATH_JARS=%CLASSPATH_JARS%
ECHO BUILD_CLASS_DIR_IMPLEMENTATION=%BUILD_CLASS_DIR_IMPLEMENTATION%
ECHO BUILD_CLASS_DIR_JUNIT=%BUILD_CLASS_DIR_JUNIT%
ECHO RUN_CLASSPATH=%RUN_CLASSPATH%
ECHO CLASS_TO_RUN=%CLASS_TO_RUN%

java -classpath %RUN_CLASSPATH% %CLASS_TO_RUN%
